# str = input('str = ')
# print('type', type(str))
# input()
# num = int(input('num = '))
# print('type', type(num))
# input()
# real = float(input('real = '))
# print('type', type(real))
# input()
logico = bool(input('logico = '))
print('type', type(logico))
input()